### ISSUE TITLE
Bug: Unable to run Streamlit App

### ISSUE THREAD

**Issue by ngv-sama** [Data-Quotient/analytiq#9]
Facing this error when running `streamlit run app.py`

`2024-09-09 23:17:54.520 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\nikhi\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 75, in exec_func_with_error_handling
    result = func()
  File "C:\Users\nikhi\AppData\Local\Programs\Python\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 574, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\nikhi\Downloads\Pari's Analyticq\analytiq\app.py", line 4, in <module>
    from pages import datasets, dq_rules
  File "C:\Users\nikhi\Downloads\Pari's Analyticq\analytiq\pages\datasets.py", line 3, in <module>
    import pandas as pd
  File "C:\Users\nikhi\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\__init__.py", line 62, in <module>
    from pandas.core.api import (
  File "C:\Users\nikhi\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\api.py", line 1, in <module>
    from pandas._libs import (
  File "C:\Users\nikhi\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\_libs\__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

**Comment by shivakharbanda** [comment]
It seems you are using some different pandas and numpy version please update them to latest versions and let me know if you face any issues

**Comment by ngv-sama** [comment]
Upgrading both is causing another library to fail. I fixed the issue by simply running a virtual env.
